### ISSUE TITLE
Add GET route to request custom cows 

### ISSUE THREAD

**Issue by adrianjmejias** [erincones/nextmoo#1]
Example 

Request: 
`curl https://erincones.github.io/moo/custom?message=test%20message&tongue=u`

Response

```
 ______________
< test message >
 --------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
             u  ||----w |
                ||     ||

```

**Comment by erincones** [comment]
This is a clone clone of the original moo project coded from scratch with Next.js. Although there are still some features to be implemented, such as the terminal on the home page, now you can request custom cows from [https://nextmoo.vercel.app/api](https://nextmoo.vercel.app/api).

The GET and POST methods are accepted with the following options:
 - `message`: The message to be printed
 - `cow`: Cow name. Any of the name of [theses files](https://github.com/erincones/nextmoo/tree/master/lib/moo/cows) without the extension. Eg: `dragon`
 - `action`: `say` or `think`
 - `mode`: Cow mode: `b`, `d`, `g`, `b`, `s`, `t`, `w` or `y`
 - `eyes`: Custom cow eyes. Only the first two characters will be used.
 - `tongue`: Custom cow tongue. Only the first two characters will be used.
 - `wrap`: Wrap column. Where the message should be wrapped. The default value is 40. To display the message exactly as provided, use a empty string as wrap value.

For GET requests the options must be provided in the query string, and for POST requests the options must be sent in the body as a JSON.

For more details about options, read the [cowsay manual](https://linux.die.net/man/1/cowsay).

**Examples:**
GET request
`curl https://nextmoo.vercel.app/api?message=test%20message&tongue=u`

Response
```
 ______________
< test message >
 --------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
             u  ||----w |
                ||     ||
```

POST request
`curl -d '{"message":"I need to finish my degree.", "cow":"turtle"}' -H "Content-Type: application/json" -X POST https://nextmoo.vercel.app/api`

Response
```
 _____________________________
< I need to finish my degree. >
 -----------------------------
    \                                  ___-------___
     \                             _-~~             ~~-_
      \                         _-~                    /~-_
             /^\__/^\         /~  \                   /    \
           /|  O|| O|        /      \_______________/        \
          | |___||__|      /       /                \          \
          |          \    /      /                    \          \
          |   (_______) /______/                        \_________ \
          |         / /         \                      /            \
           \         \^\\         \                  /               \     /
             \         ||           \______________/      _-_       //\__//
               \       ||------_-~~-_ ------------- \ --/~   ~\    || __/
                 ~-----||====/~     |==================|       |/~~~~~
                  (_(__/  ./     /                    \_\      \.
                         (_(___/                         \_____)_)
```

**Extra:** You can also use this options in the query string of the [home page](https://nextmoo.vercel.app/?message=maldito%20socialismo) to show custom cows at page load. Enjoy!
